export const ERROR_MESSAGES = {
  PASSWORD_LEAST_8_CHARACTER: "Mật khẩu ít nhất 8 ký tự.",
  EMAIL_REQUIRED: "Trường email là bắt buộc.",
  PASSWORD_REQUIRED: "Trường mật khẩu là bắt buộc.",
  CONFIRM_PASSWORD_REQUIRED: "Trường xác thực mật khẩu là bắt buộc.",
  PASSWORD_MATCH: "Mật khẩu phải trùng khớp.",
  INVALID_EMAIL: "Email không hợp lệ.",
  NAME_REQUIRED: "Trường tên là bắt buộc",
  NAME_LEAST_6_CHARACTER: "Tên ít nhất 6 ký tự.",
  NAME_MAX_30_CHARACTER: "Tên nhiều nhất 30 ký tự.",
  MIN_1: "Không được ít hơn 1",
  MUST_NUMBER: "Phải là số.",
  INVALID_PHONE: "Số điện thoại không hợp lệ.",
  REQUIRED_FIELD: "Trường này là bắt buộc!",
  NOT_BEFORE_TODAY: "Không được trước ngày hiện tại!",
  COME_OUT: "Thời gian ra phải sau thời gian vào!",
  REJECTED_SUCCESS: "Hủy dịch vụ thành công",
  FEEDBACK_SUCCESS: "Gửi đánh giá thành công",
  //dish
  DISH_NAME_REQUIRED: "Tên món ăn không được để trống",
  PRICE_REQUIRED: "Giá tiền không được để trống",
  PRICE_MUST_NUMBER: "Giá tiền phải là một số",
  PRICE_MIN_0: "Giá tiền không được nhỏ hơn 0",
  PRICE_MAX_1_BILLION: "Giá tiền không được lớn hơn 1 tỷ",
  TYPEID_REQUIRED: "Loại món ăn không được để trống",

  //service
  SERVICE_REQUIRED: "Giá tiền không được để trống",
  CAPACITY_REQUIRED: "Sức chứa không được để trống",
  CAPACITY_MUST_NUMBER: "Sức chứa phải là một số",
  CAPACITY_MIN_1: "Sức chứa không được nhỏ hơn 1",
};

export const MESSAGE_SUCCESS = {
  UPDATED_SUCCESS: "Cập nhật thành công!",
  CREATED_USER_SUCCESS: "Tạo tài khoản thành công",
  DELETE_USER_SUCCESS: "Xóa tài khoản thành công",
  CREATE_DISH_SUCCESS: "Tạo món ăn thành công",
  DELETE_DISH_SUCCESS: "Xóa món ăn thành công",
  CREATE_SERVICE_SUCCESS: "Tạo dịch vụ thành công",
  DELETE_SERVICE_SUCCESS: "Xóa dịch vụ thành công",
  CREATE_BOOKING_SUCCESS: "Tạo đơn hàng thành công",
  DELETE_BOOKING_SUCCESS: "Xóa đơn hàng thành công",
  CREATE_COMBO_SUCCESS: "Tạo menu món ăn thành công",
  DELETE_COMBO_SUCCESS: "Xóa menu món ăn thành công",
  CHOOSE_FOOD: "Vui lòng chọn món ăn",
};
