export const ERROR_MESSAGES = {
  PASSWORD_LEAST_8_CHARACTER: "Mật khẩu ít nhất 8 ký tự.",
  EMAIL_REQUIRED: "Trường email là bắt buộc.",
  PASSWORD_REQUIRED: "Trường mật khẩu là bắt buộc.",
  CONFIRM_PASSWORD_REQUIRED: "Trường xác thực mật khẩu là bắt buộc.",
  PASSWORD_MATCH: "Mật khẩu phải trùng khớp.",
  INVALID_EMAIL: "Email không hợp lệ.",
  NAME_REQUIRED: "Trường tên là bắt buộc",
  NAME_LEAST_6_CHARACTER: "Tên ít nhất 6 ký tự.",
  NAME_MAX_11_CHARACTER: "Tên nhiều nhất 11 ký tự.",
  MIN_1: "Không được ít hơn 1",
  MUST_NUMBER: "Phải là số.",
  INVALID_PHONE: "Số điện thoại không hợp lệ.",
  REQUIRED_FIELD: "Trường này là bắt buộc!",
  NOT_BEFORE_TODAY: "Không được trước ngày hiện tại!",
  COME_OUT: "Thời gian ra phải sau thời gian vào!",
};