export const NEXT_UPLOAD_PRESET = process.env.NEXT_PUBLIC_UPLOAD_PRESET;
export const NEXT_CLOUDINARY_NAME =
  process.env.NEXT_PUBLIC_CLOUDINARY_NAME;
export const NEXT_URL_CLOUD = process.env.NEXT_PUBLIC_URL_CLOUD;
export const NEXT_PUBLIC_PK_STRIPE_KEY = process.env.NEXT_PUBLIC_PK_STRIPE_KEY || "pk_test_51Lg6bmChkdjnRPrOTY98WTA6M1GbVXByE9YZYp64FFmvWeCmNBFetNdChmFdaXeYX5EY07j6XXGIvA0tZgsl8lAH009n3IJeNK";
